// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rxrvgwlvqsnjbtnifwcc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ4cnZnd2x2cXNuamJ0bmlmd2NjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NDIzNzcsImV4cCI6MjA2NTExODM3N30.NfuHCsafiHSsJwvCAp0MYmk0o9rTng3SHJaEmPebq4g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);